More_xp_from:
  Crafting_expensive_items: true
  Farming: true
  Advancements: true
  Tools_breaking: true
Xp_amounts:
  Crafted_items:
    - BOOKSHELF;0.2
    - BUCKET;0.1
    - CAULDRON;0.2
    - ANVIL;1
    - BEACON;10
    - DIAMOND_AXE;0.5
    - DIAMOND_BOOTS;0.5
    - DIAMOND_CHESTPLATE;0.5
    - DIAMOND_HELMET;0.5
    - DIAMOND_HOE;0.5
    - DIAMOND_LEGGINGS;0.5
    - DIAMOND_PICKAXE;0.5
    - DIAMOND_SHOVEL;0.5
    - DIAMOND_SWORD;0.5
    - GOLDEN_APPLE;0.5
    - ENDER_CHEST;0.1
    - HOPPER;0.1
    - IRON_AXE;0.2
    - IRON_BOOTS;0.2
    - IRON_CHESTPLATE;0.2
    - IRON_HELMET;0.2
    - IRON_HOE;0.2
    - IRON_LEGGINGS;0.2
    - IRON_PICKAXE;0.2
    - IRON_SHOVEL;0.2
    - IRON_SWORD;0.2
    - JUKEBOX;0.4
    - PISTON;0.1
    - SHIELD;0.1
  Farming:
    - WHEAT;0.1
    - POTATO;0.1
    - CARROT;0.1
    - BEETROOT;0.1
    - NETHER_WART;0.1
  Advancements: 5
  Tools_breaking:
    - DIAMOND_AXE;0.5
    - DIAMOND_BOOTS;0.5
    - DIAMOND_CHESTPLATE;0.5
    - DIAMOND_HELMET;0.5
    - DIAMOND_HOE;0.5
    - DIAMOND_LEGGINGS;0.5
    - DIAMOND_PICKAXE;0.5
    - DIAMOND_SHOVEL;0.5
    - DIAMOND_SWORD;0.5
    - IRON_AXE;0.2
    - IRON_BOOTS;0.2
    - IRON_CHESTPLATE;0.2
    - IRON_HELMET;0.2
    - IRON_HOE;0.2
    - IRON_LEGGINGS;0.2
    - IRON_PICKAXE;0.2
    - IRON_SHOVEL;0.2
    - IRON_SWORD;0.2
    - GOLDEN_AXE;0.1
    - GOLDEN_BOOTS;0.1
    - GOLDEN_CHESTPLATE;0.1
    - GOLDEN_HELMET;0.1
    - GOLDEN_HOE;0.1
    - GOLDEN_LEGGINGS;0.1
    - GOLDEN_PICKAXE;0.1
    - GOLDEN_SHOVEL;0.1
    - GOLDEN_SWORD;0.1
    - STONE_AXE;0.1
    - STONE_HOE;0.1
    - STONE_PICKAXE;0.1
    - STONE_SHOVEL;0.1
    - STONE_SWORD;0.1
    - WOODEN_AXE;0.1
    - WOODEN_HOE;0.1
    - WOODEN_PICKAXE;0.1
    - WOODEN_SHOVEL;0.1
    - WOODEN_SWORD;0.1
    - LEATHER_BOOTS;0.1
    - LEATHER_CHESTPLATE;0.1
    - LEATHER_HELMET;0.1
    - LEATHER_LEGGINGS;0.1
    - FISHING_ROD;0.1
    - CROSSBOW;0.1
    - BOW;0.1
    - TRIDENT;0.2
