Recipes:
  Toast:
    In:
      Item: BREAD
    Out:
      Item: BREAD
      Name: 'Toast'
      Saturation: 1
    Campfire: true
    Smoker: true
    Cooking_time_seconds: 5
    Xp: 0.0
  Potato_Mash:
    In:
      Item: BAKED_POTATO
    Out:
      Item: BAKED_POTATO
      Name: 'Potato Mash'
      Saturation: 1
    Campfire: true
    Smoker: true
    Cooking_time_seconds: 5
    Xp: 0.0
  Smelt_Gold_Helmet:
    In:
      Item: GOLDEN_HELMET
    Out:
      Item: GOLD_NUGGET
      Amount: 3
    Blast: true
  Smelt_Gold_Chest:
    In:
      Item: GOLDEN_CHESTPLATE
    Out:
      Item: GOLD_NUGGET
      Amount: 6
    Blast: true
  Smelt_Gold_Pants:
    In:
      Item: GOLDEN_LEGGINGS
    Out:
      Item: GOLD_NUGGET
      Amount: 5
    Blast: true
  Smelt_Gold_Boots:
    In:
      Item: GOLDEN_BOOTS
    Out:
      Item: GOLD_NUGGET
      Amount: 2
    Blast: true
  Smelt_Gold_Sword:
    In:
      Item: GOLDEN_SWORD
    Out:
      Item: GOLD_NUGGET
      Amount: 2
    Blast: true