name: LittleChef
author: Rsl1122
main: com.djrapitops.littlechef.LittleChef
version: 1.1.1
api-version: 1.14

commands:
  littlechef:
    usage: /littlechef reload
    description: reloads littlechef
    permission: littlechef.reload

permissions:
  littlechef.reload:
    description: reload command
    default: op