Compostable:
  30_percent:
    - BAMBOO
    - GRASS
    - COBWEB
    - STRING
    - DEAD_BUSH
    - DEAD_BRAIN_CORAL
    - DEAD_BUBBLE_CORAL
    - DEAD_FIRE_CORAL
    - DEAD_HORN_CORAL
    - DEAD_TUBE_CORAL
    - BRAIN_CORAL
    - BUBBLE_CORAL
    - FIRE_CORAL
    - HORN_CORAL
    - TUBE_CORAL
    - DRIED_KELP
    - EGG
    - ROTTEN_FLESH
    - SPIDER_EYE
    - STRING
    - SUGAR
  50_percent:
    - BEEF
    - BEETROOT_SOUP
    - CHICKEN
    - COD
    - MUTTON
    - PORKCHOP
    - RABBIT
    - SALMON
    - DEAD_BRAIN_CORAL_BLOCK
    - DEAD_BUBBLE_CORAL_BLOCK
    - DEAD_FIRE_CORAL_BLOCK
    - DEAD_HORN_CORAL_BLOCK
    - DEAD_TUBE_CORAL_BLOCK
    - BRAIN_CORAL_BLOCK
    - BUBBLE_CORAL_BLOCK
    - FIRE_CORAL_BLOCK
    - HORN_CORAL_BLOCK
    - TUBE_CORAL_BLOCK
    - DRIED_KELP_BLOCK
    - FERMENTED_SPIDER_EYE
    - GLISTERING_MELON_SLICE
    - PUFFERFISH
    - TROPICAL_FISH
    - TURTLE_EGG
  65_percent:
    - COOKED_BEEF
    - COOKED_CHICKEN
    - COOKED_COD
    - COOKED_MUTTON
    - COOKED_PORKCHOP
    - COOKED_RABBIT
    - COOKED_SALMON
    - HONEYCOMB
    - PHANTOM_MEMBRANE
    - POISONOUS_POTATO
    - RABBIT_FOOT
    - RABBIT_STEW
    - SUSPICIOUS_STEW
  85_percent:
    - HONEY_BLOCK
    - HONEYCOMB_BLOCK
  100_percent:
    - DRAGON_HEAD
    - ZOMBIE_HEAD