Announce_banner_rewards: true
Reward_message: "&2%player% has defeated %n%th %mob%!"
Reward_banner_every_x_kill:
  BAT: 25
  BEE: 25
  BLAZE: 50
  CAT: 25
  CAVE_SPIDER: 25
  CHICKEN: 50
  COD: 25
  COW: 50
  CREEPER: 50
  DOLPHIN: 25
  DONKEY: 25
  DROWNED: 50
  ELDER_GUARDIAN: 5
  ENDER_DRAGON: 5
  ENDERMAN: 50
  EVOKER: 25
  FOX: 25
  GHAST: 25
  GUARDIAN: 50
  HOGLIN: 25
  HORSE: 25
  HUSK: 50
  ILLUSIONER: 25
  IRON_GOLEM: 25
  LLAMA: 25
  MAGMA_CUBE: 25
  MULE: 25
  MUSHROOM_COW: 25
  OCELOT: 25
  PANDA: 25
  PARROT: 25
  PHANTOM: 25
  PIG: 50
  PIGLIN: 25
  PIGLIN_BRUTE: 25
  POLAR_BEAR: 25
  PUFFERFISH: 25
  RABBIT: 25
  RAVAGER: 25
  SALMON: 25
  SHEEP: 50
  SHULKER: 25
  SILVERFISH: 25
  SLIME: 50
  SNOWMAN: 25
  SPIDER: 50
  SQUID: 50
  STRAY: 25
  STRIDER: 25
  TURTLE: 25
  TROPICAL_FISH: 25
  VEX: 25
  WITCH: 25
  WITHER: 5
  WITHER_SKELETON: 25
  ZOGLIN: 25
  ZOMBIE: 50