name: MobBanners
author: AuroraLS3
main: com.djrapitops.banners.MobBanners
version: 1.0.2
api-version: 1.16

commands:
  banners:
    usage: /banners reload
    description: reloads MobBanners
    permission: banners.reload

permissions:
  banners.reload:
    description: reload command
    default: op