name: LittleFX
author: Rsl1122
main: com.djrapitops.littlefx.LittleFX
version: 1.1.0
api-version: 1.13
softdepend:
  - WorldGuard

commands:
  littlefx:
    usage: /littlefx reload
    description: reloads littlefx

permissions:
  littlefx.reload:
    description: reload command
    default: OP